'use client';

import { ChangeEvent, useMemo, useState } from 'react';
import { ArrowLeft, Bell, Check, ChevronDown, ImagePlus, LayoutDashboard, MoreHorizontal, Package, Plus, Search, Settings2, ShoppingBag, Tags, Upload, X } from 'lucide-react';

type AdminProduct = { id: number; name: string; category: string; price: string; stock: number; status: 'Ativo' | 'Rascunho'; sizes: number[]; image: string };
const initialProducts: AdminProduct[] = [
  { id: 1, name: 'Brasil Logo Branco', category: 'Havaianas', price: 'R$ 39,90', stock: 17, status: 'Ativo', sizes: [33, 35, 36, 37, 38, 40], image: '/products/havaianas-branco.png' },
  { id: 2, name: 'Top Rosé', category: 'Havaianas', price: 'R$ 34,90', stock: 13, status: 'Ativo', sizes: [34, 36, 37, 38, 39], image: '/products/havaianas-branco.png' },
  { id: 3, name: 'Slim Preto', category: 'Havaianas', price: 'R$ 44,90', stock: 14, status: 'Ativo', sizes: [33, 34, 35, 37, 38, 39, 40], image: '/products/havaianas-branco.png' },
  { id: 4, name: 'Top Max Comfort', category: 'Havaianas', price: 'R$ 59,90', stock: 10, status: 'Rascunho', sizes: [35, 36, 37, 39, 40], image: '/products/havaianas-branco.png' },
];
const adminSizes = [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46];

export default function AdminPage() {
  const [items, setItems] = useState(initialProducts);
  const [search, setSearch] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [importNotice, setImportNotice] = useState(false);
  const [form, setForm] = useState({ name: '', category: 'Havaianas', price: '', description: '', sizes: [] as number[], image: '/products/havaianas-branco.png' });
  const visibleItems = useMemo(() => items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase())), [items, search]);
  function handleImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setForm((current) => ({ ...current, image: URL.createObjectURL(file) })); }
  function toggleSize(size: number) { setForm((current) => ({ ...current, sizes: current.sizes.includes(size) ? current.sizes.filter((item) => item !== size) : [...current.sizes, size] })); }
  function saveProduct() { if (!form.name.trim() || !form.price.trim()) return; setItems((current) => [...current, { id: Date.now(), name: form.name, category: form.category, price: `R$ ${form.price}`, stock: form.sizes.length, status: 'Rascunho', sizes: form.sizes, image: form.image }]); setForm({ name: '', category: 'Havaianas', price: '', description: '', sizes: [], image: '/products/havaianas-branco.png' }); setShowForm(false); }

  return <main className="admin-shell">
    <aside className="admin-sidebar"><a href="/" className="admin-brand"><span className="admin-brand-mark">mv</span><span><strong>MEU VÍCIO</strong><small>painel da loja</small></span></a><div className="admin-menu-label">menu principal</div><nav className="admin-menu"><a className="active" href="#visao-geral"><LayoutDashboard size={17} /> Visão geral</a><a href="#produtos"><Package size={17} /> Produtos <span>4</span></a><a href="#categorias"><Tags size={17} /> Categorias</a><a href="#pedidos"><ShoppingBag size={17} /> Pedidos</a></nav><div className="admin-menu-label settings-label">configurações</div><nav className="admin-menu"><a href="#configuracoes"><Settings2 size={17} /> Preferências</a></nav><div className="admin-sidebar-bottom"><div className="admin-user-avatar">MV</div><div><strong>Meu Vício</strong><span>Administrador</span></div><MoreHorizontal size={17} /></div></aside>
    <section className="admin-content"><header className="admin-topbar"><div><span className="admin-breadcrumb">Painel / Visão geral</span><h1>Bom dia, Meu Vício <span>✦</span></h1></div><div className="admin-top-actions"><button type="button" aria-label="Notificações"><Bell size={19} /></button><a className="view-store" href="/" target="_blank" rel="noreferrer">Ver catálogo <ArrowLeft size={15} /></a></div></header>
      <div className="admin-main" id="visao-geral">{importNotice && <div className="import-notice"><div><span className="notice-icon"><Check size={16} /></span><div><strong>Drive usado somente para a primeira carga</strong><p>Depois da importação, novos produtos, fotos e estoques serão atualizados diretamente neste painel.</p></div></div><button type="button" onClick={() => setImportNotice(false)} aria-label="Fechar aviso"><X size={17} /></button></div>}
        <div className="admin-stats"><div className="stat-card accent"><span className="stat-icon"><Package size={18} /></span><div><small>Produtos ativos</small><strong>03</strong><em>+1 nesta semana</em></div></div><div className="stat-card"><span className="stat-icon green"><ShoppingBag size={18} /></span><div><small>Pares em estoque</small><strong>44</strong><em>por numeração</em></div></div><div className="stat-card"><span className="stat-icon sand"><Tags size={18} /></span><div><small>Categorias</small><strong>01</strong><em>Havaianas</em></div></div><div className="stat-card"><span className="stat-icon lilac"><ImagePlus size={18} /></span><div><small>Imagens cadastradas</small><strong>04</strong><em>armazenamento próprio</em></div></div></div>
        <div className="admin-section-head" id="produtos"><div><span className="admin-kicker">catálogo</span><h2>Produtos cadastrados</h2></div><div className="admin-head-actions"><button type="button" className="import-button" onClick={() => setImportNotice(true)}><Upload size={16} /> Importar primeira carga</button><button type="button" className="new-product-button" onClick={() => setShowForm(true)}><Plus size={17} /> Novo produto</button></div></div>
        <div className="admin-toolbar"><div className="admin-search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nome do produto" /></div><button type="button" className="status-filter">Todos os status <ChevronDown size={15} /></button></div>
        <div className="products-table-wrap"><table className="products-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque total</th><th>Tamanhos com estoque</th><th>Status</th><th></th></tr></thead><tbody>{visibleItems.map((item) => <tr key={item.id}><td><div className="table-product"><img src={item.image} alt="" /><strong>{item.name}</strong></div></td><td>{item.category}</td><td className="table-price">{item.price}</td><td><strong>{item.stock}</strong> pares</td><td><div className="table-sizes">{item.sizes.slice(0, 5).map((size) => <span key={size}>{size}</span>)}{item.sizes.length > 5 && <span>+{item.sizes.length - 5}</span>}</div></td><td><span className={item.status === 'Ativo' ? 'status active' : 'status draft'}><i />{item.status}</span></td><td><button className="row-menu" type="button" aria-label={`Opções de ${item.name}`}><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div>
        <div className="admin-help-card"><div className="help-illustration"><ImagePlus size={27} /></div><div><span className="admin-kicker">próximo passo</span><h3>Cadastre os produtos da loja</h3><p>Use o botão de novo produto para adicionar fotos, categorias, preços e estoque separado por tamanho.</p></div><button type="button" className="secondary-admin-button" onClick={() => setShowForm(true)}>Cadastrar produto <Plus size={15} /></button></div>
      </div></section>
    {showForm && <div className="admin-modal-backdrop" role="presentation" onClick={() => setShowForm(false)}><div className="admin-form-modal" role="dialog" aria-modal="true" aria-labelledby="admin-form-title" onClick={(event) => event.stopPropagation()}><div className="admin-form-header"><div><span className="admin-kicker">novo cadastro</span><h2 id="admin-form-title">Adicionar produto</h2></div><button type="button" onClick={() => setShowForm(false)} aria-label="Fechar"><X size={19} /></button></div><div className="admin-form-body"><label>Nome do produto<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Havaianas Brasil Logo Branco" /></label><div className="admin-form-grid"><label>Categoria<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option>Havaianas</option><option>Outros Calçados</option></select></label><label>Preço<input value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} placeholder="39,90" /></label></div><label>Descrição<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Descreva o produto brevemente" rows={3} /></label><label className="upload-field"><span>Imagem principal</span><div><ImagePlus size={18} /><strong>Selecione uma foto do produto</strong><small>PNG ou JPG • imagem quadrada recomendada</small><input type="file" accept="image/png,image/jpeg" onChange={handleImage} /></div></label><fieldset><legend>Tamanhos disponíveis</legend><div className="admin-size-grid">{adminSizes.map((size) => <label key={size} className={form.sizes.includes(size) ? 'admin-size selected' : 'admin-size'}><input type="checkbox" checked={form.sizes.includes(size)} onChange={() => toggleSize(size)} /><span>{size}</span></label>)}</div></fieldset></div><div className="admin-form-footer"><button type="button" className="cancel-button" onClick={() => setShowForm(false)}>Cancelar</button><button type="button" className="new-product-button" onClick={saveProduct}>Salvar produto <Check size={16} /></button></div></div></div>}
  </main>;
}
